Feature/1292v2
massiveinteractive/cordova-plugin-inappbrowser pull request #7
Opened 2016-11-23 16:41 UTC by septronic2

### Platforms affected

### What does this PR do?

### What testing has been done on this change?

### Checklist
- [ ] [ICLA](http://www.apache.org/licenses/icla.txt) has been signed and submitted to secretary@apache.org.
- [ ] [Reported an issue](http://cordova.apache.org/contribute/issues.html) in the JIRA database
- [ ] Commit message follows the format: "CB-3232: (android) Fix bug with resolving file paths", where CB-xxxx is the JIRA ID & "android" is the platform affected.
- [ ] Added automated test coverage as appropriate for this change.

2016-11-28 15:41 UTC, septronic2 commented
@shoebox @massivekarenwong Please review this and if we need to change anything let me know. Thanks

2017-01-18 18:44 UTC, septronic2 commented
@massivekarenwong I finally made the changes to the plugin. Can you please review it and we can remove the button. Thanks

2017-01-19 10:31 UTC, massivekarenwong commented on plugin.xml
> +		<framework src="CoreGraphics.framework" />
outdent this

2017-01-19 10:33 UTC, massivekarenwong commented on src/ios/CDVInAppBrowser.m
> +		if (array.count>2)
space before and after >

2017-01-19 10:33 UTC, massivekarenwong commented on src/ios/CDVInAppBrowser.m
> +		else if (array.count==2)
space before and after ==

2017-01-19 10:33 UTC, massivekarenwong commented on src/ios/CDVInAppBrowser.m
> +		if (array.count<2)
space before and after <

2017-01-19 10:35 UTC, massivekarenwong requested changes

2017-01-19 10:35 UTC, massivekarenwong commented on src/ios/CDVInAppBrowser.m
> +			NSMutableURLRequest *mutable_request= [request mutableCopy];
space before =

2017-01-19 11:38 UTC, massivekarenwong requested changes

2017-01-19 11:38 UTC, massivekarenwong commented on src/ios/CDVInAppBrowser.m
> +	self.addressLabel.text = @"Loading...";
As discussed, revert all similar changes

2017-01-19 11:38 UTC, massivekarenwong commented on README.md
Please update the README with the newly added features as well

2017-01-19 11:38 UTC, massivekarenwong commented on src/ios/CDVInAppBrowser.m
> +													   action:@selector(close)];
revert this change, we shouldn't be hardcoding title to "Close"

2017-01-19 11:38 UTC, massivekarenwong commented on src/ios/CDVInAppBrowser.m
> +- (id)initWithOptions:(NSString*)optionStrings
You are not using optionStrings at all in this method. The change is not necessary. Revert it back to how it used to be

2017-01-19 11:38 UTC, massivekarenwong commented on src/ios/CDVInAppBrowser.m
> +		self.closebuttoncaption = closeString;
I don't think this is necessary. Keep self.closebuttoncaption is already set to nil in earlier lines

2017-01-19 11:38 UTC, massivekarenwong commented on src/ios/CDVInAppBrowser.m
> +	[obj setValue:[numberFormatter numberFromString:@"1.0"] forKey:@"alphagradient2"];
can we move all of the default values to init?

2017-01-19 11:38 UTC, massivekarenwong commented on src/ios/CDVInAppBrowser.m
> -			[numberFormatter setAllowsFloats:YES];
After moving all default value settings to init, you will have to keep these lines

2017-01-19 11:38 UTC, massivekarenwong commented on src/ios/WebViewJavascriptBridge/WebViewJavascriptBridgeBase.m
> +//
remove commented out lines

2017-01-19 11:38 UTC, massivekarenwong commented on src/ios/WebViewJavascriptBridge/WebViewJavascriptBridgeBase.m
> +//	return YES;
remove commented out lines

2017-01-19 11:38 UTC, massivekarenwong commented on src/ios/WebViewJavascriptBridge/WebViewJavascriptBridgeBase.m
> +//	return YES;
remove commented out lines

2017-01-19 11:38 UTC, massivekarenwong commented on src/ios/WebViewJavascriptBridge/WebViewJavascriptBridge_JS.m
> +			// console.log("WebViewJavascriptBridge: ERROR:" + msg + "@" + url + ":" + line);
include this back in for debugging

2017-01-19 11:38 UTC, massivekarenwong commented on src/ios/WebViewJavascriptBridge/WebViewJavascriptBridge_JS.m
> +		// console.log(handler)
remove comment

2017-01-19 11:38 UTC, massivekarenwong commented on src/ios/WebViewJavascriptBridge/WebViewJavascriptBridge_JS.m
> +					// console.log("WebViewJavascriptBridge: WARNING: no handler for message from ObjC:", message);
uncomment this

2017-01-19 13:45 UTC, massivekarenwong requested changes

2017-01-19 13:45 UTC, massivekarenwong commented on README.md
> +    - __hideallbuttons__: Set to 'YES' or 'No' (set to No by default). This will remove all buttons from the view (this only effects native buttons)
I believe it should be 'yes' or 'no' to keep it consistent with the other options

2017-01-19 13:45 UTC, massivekarenwong commented on README.md
> +    - __hideallbuttons__: Set to 'YES' or 'No' (set to No by default). This will remove all buttons from the view (this only effects native buttons)
Can you also add the headers arguments after option in line 86 and add a description below as well?

2017-01-19 16:25 UTC, massivekarenwong approved these changes

2017-01-19 16:32 UTC, merged